combPower:
	export CP=31250;\
		export CFG=comb; \
		joules -no_gui -add_license Genus_Synthesis -f scr/activityBased.tcl
fplPower:
	export CP=31250;\
		export CFG=fpl; \
		joules -no_gui -add_license Genus_Synthesis -f scr/activityBased.tcl
fdcPower:
	export FS_CP=31250;\
		joules -no_gui -add_license Genus_Synthesis -f scr/FDCactivityBased.tcl
mulfdcPower:
	export FS_CP=31250;\
		joules -no_gui -add_license Genus_Synthesis -f scr/MULFDCactivityBased.tcl
