combPower:
	export CP=31250;\
		export CFG=comb; \
		joules -no_gui -add_license Genus_Synthesis -f scr/activityBased.tcl
fplPower:
	export CP=31250;\
		export CFG=fpl; \
		joules -no_gui -add_license Genus_Synthesis -f scr/activityBased.tcl
